#!/usr/bin/env bash
# install.sh - portable agentmux installer. Run inside WSL:
#
#   bash <(tr -d '\r' < /mnt/c/path/to/agentmux/install.sh)
#
# The tr strips CRs, because this file is usually authored on Windows.
#
# or on macOS, from the checkout (needs Homebrew's bash, tmux and python3):
#
#   brew install bash tmux python node && bash install.sh
#
# Assumes nothing about the username, distro, drive letter, checkout location
# or node version. Everything is discovered at run time.

set -uo pipefail

info() { printf '  %s\n' "$*"; }
warn() { printf 'WARN: %s\n' "$*" >&2; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

# Where this script lives, even when invoked via process substitution (where
# $0 is /dev/fd/N and BASH_SOURCE is useless). Fall back to asking the user.
find_repo() {
  local src="${BASH_SOURCE[0]:-}" d
  if [ -n "$src" ] && [ -f "$src" ]; then
    d="$(cd "$(dirname "$src")" && pwd)"
    [ -f "$d/agentmux.sh" ] && { printf '%s' "$d"; return 0; }
  fi
  # Invoked from a pipe or fd: accept an explicit override.
  if [ -n "${AGENTMUX_REPO:-}" ] && [ -f "$AGENTMUX_REPO/agentmux.sh" ]; then
    printf '%s' "$(cd "$AGENTMUX_REPO" && pwd)"; return 0
  fi
  return 1
}

case "$(uname -s)" in Darwin) OS=macos ;; *) OS=linux ;; esac

echo "agentmux installer ($OS)"
echo

REPO="$(find_repo)" || die "cannot locate agentmux.sh.
Re-run with the checkout path, e.g.:
  AGENTMUX_REPO=/mnt/c/path/to/agentmux bash <(tr -d '\r' < /mnt/c/path/to/agentmux/install.sh)"
info "harness source : $REPO/agentmux.sh"

# --- prerequisites ----------------------------------------------------------

# Homebrew is not on PATH in a non-login shell; find it the way its installer does.
if [ "$OS" = macos ] && ! command -v brew >/dev/null 2>&1; then
  for b in /opt/homebrew/bin/brew /usr/local/bin/brew; do
    [ -x "$b" ] && { eval "$("$b" shellenv)"; break; }
  done
fi

if [ "$OS" = linux ]; then
  command -v wslpath >/dev/null 2>&1 || warn "wslpath missing - Windows path translation (--cwd 'C:\\...') will not work"
fi
if command -v tmux >/dev/null 2>&1; then
  info "tmux           : $(tmux -V)"
elif [ "$OS" = macos ]; then
  die "tmux not installed. Install it first:  brew install tmux"
else
  die "tmux not installed. Install it first:  sudo apt update && sudo apt install -y tmux"
fi

# The harness needs bash 4.1+ (exec {fd}>, associative arrays). macOS /bin/bash is
# 3.2 and will stay that way, so the launcher is pinned to an absolute newer bash
# rather than to whichever bash happens to be first on PATH.
HARNESS_BASH=""
for b in "$(command -v bash 2>/dev/null)" /opt/homebrew/bin/bash /usr/local/bin/bash /bin/bash; do
  [ -n "$b" ] && [ -x "$b" ] || continue
  if "$b" -c '[ "${BASH_VERSINFO[0]}" -ge 5 ] || { [ "${BASH_VERSINFO[0]}" -eq 4 ] && [ "${BASH_VERSINFO[1]}" -ge 1 ]; }'; then
    HARNESS_BASH="$b"; break
  fi
done
[ -n "$HARNESS_BASH" ] || die "bash 4.1+ not found (macOS ships 3.2). Install it:  brew install bash"
info "bash           : $HARNESS_BASH ($("$HARNESS_BASH" -c 'echo $BASH_VERSION'))"

# Python 3.10+: macOS /usr/bin/python3 is 3.9, so name the one the panes will use.
if python3 -c 'import sys; sys.exit(sys.version_info < (3, 10))' 2>/dev/null; then
  info "python3        : $(command -v python3) ($(python3 -V 2>&1))"
else
  warn "python3 on PATH is older than 3.10 ($(command -v python3)). Put a newer one first:
       $( [ "$OS" = macos ] && echo 'brew install python   # and keep /opt/homebrew/bin ahead of /usr/bin' || echo 'sudo apt install -y python3' )"
fi

NODE_BIN="$(ls -d "$HOME"/.nvm/versions/node/*/bin 2>/dev/null | sort -V | tail -1)"
if [ -n "$NODE_BIN" ]; then
  info "node (nvm)     : $("$NODE_BIN/node" --version 2>/dev/null)"
elif [ "$OS" = macos ]; then
  # No Windows shims to outrank on a Mac: the Homebrew node on PATH is the right one.
  if command -v node >/dev/null 2>&1; then
    NODE_BIN="$(dirname "$(command -v node)")"
    info "node           : $(command -v node) ($(node --version 2>/dev/null))"
  else
    warn "node not found. Agent CLIs installed with npm need it:  brew install node"
  fi
else
  warn "no nvm-managed node found. The harness prepends the newest nvm node bin to
       each pane's PATH so agent CLIs resolve to Linux binaries instead of the
       Windows npm shims. Without it, 'codex' may resolve to a Windows shim that
       cannot run under Linux. Install node via nvm before spawning codex."
fi

# --- launcher ---------------------------------------------------------------

BIN="$HOME/.local/bin"
mkdir -p "$BIN"
cat > "$BIN/agentmux" <<LAUNCHER
#!$HARNESS_BASH
# Generated by agentmux install.sh on $(date -Is 2>/dev/null || date +%Y-%m-%dT%H:%M:%S%z).
# Strips CRs from the Windows-authored source at run time, so editing the .sh
# from Windows cannot break it. Do not invoke the .sh directly.
# AGENTMUX_REPO lets agentmux.sh find sibling tooling (taskmgmt/task.py). The
# harness cannot derive its own location: it runs via process substitution, so
# \$0 is /dev/fd/N and BASH_SOURCE is useless.
# The bash is absolute because macOS /bin/bash (3.2) cannot run the harness.
export AGENTMUX_REPO="$REPO"
exec "$HARNESS_BASH" <(tr -d "\r" < "$REPO/agentmux.sh") "\$@"
LAUNCHER
chmod +x "$BIN/agentmux"
info "launcher       : $BIN/agentmux"

case ":$PATH:" in
  *":$BIN:"*) ;;
  *) warn "$BIN is not on your PATH. Add to ~/.bashrc:
         export PATH=\"\$HOME/.local/bin:\$PATH\"" ;;
esac

# --- agent CLIs -------------------------------------------------------------

echo
if [ "$OS" = macos ]; then
  echo "agent CLIs:"
else
  echo "agent CLIs (must be Linux builds - Windows npm shims fail under WSL):"
fi
PATH="${NODE_BIN:-}:$PATH"
for cli in codex claude; do
  p="$(command -v "$cli" 2>/dev/null)"
  if [ -z "$p" ]; then
    info "$cli : MISSING   -> npm install -g $( [ "$cli" = codex ] && echo '@openai/codex@latest' || echo '@anthropic-ai/claude-code' )"
  elif case "$p" in /mnt/*) true ;; *) false ;; esac; then
    warn "$cli resolves to a WINDOWS path ($p) - it will crash inside WSL.
       Install the Linux build: npm install -g $( [ "$cli" = codex ] && echo '@openai/codex@latest' || echo '@anthropic-ai/claude-code' )"
  else
    info "$cli : $p"
  fi
done

# --- Windows entry point ----------------------------------------------------

if command -v wslpath >/dev/null 2>&1; then
  WINREPO="$(wslpath -w "$REPO" 2>/dev/null)"
  if [ -n "$WINREPO" ]; then
    echo
    echo "Optional - drive it from Windows by adding this to your user PATH:"
    info "$WINREPO"
    info "(then 'agentmux list' works from cmd/PowerShell via agentmux.cmd)"
    info "NOTE: the .cmd entry point discards exit codes and puts arguments on a"
    info "      cmd.exe pipeline. Prefer driving the harness from WSL directly."
  fi
fi

# --- macOS: dashboard at login -----------------------------------------------

if [ "$OS" = macos ]; then
  AGENTS="$HOME/Library/LaunchAgents"
  PLIST="$AGENTS/com.agentmux.ccc-dashboard.plist"
  mkdir -p "$AGENTS"
  # PATH for launchd jobs is minimal; give the dashboard the same tools this shell found.
  LAUNCH_PATH="$BIN:$(dirname "$(command -v python3)"):$(dirname "$(command -v tmux)")${NODE_BIN:+:$NODE_BIN}:/usr/bin:/bin:/usr/sbin:/sbin"
  sed -e "s#@REPO@#$REPO#g" -e "s#@PATH@#$LAUNCH_PATH#g" -e "s#@BASH@#$HARNESS_BASH#g" \
      "$REPO/dashboard/ccc-dashboard.plist" > "$PLIST"
  echo
  info "launchd agent  : $PLIST"
  cat <<NEXT_MAC

Next steps (macOS)
  1. Start the dashboard now and at every login:
       launchctl bootstrap gui/\$(id -u) "$PLIST"
     then open http://127.0.0.1:8787  (log: /tmp/ccc-dashboard.launchd.log)
  2. Log in to each agent CLI (interactive, one time):
       codex login
       claude          # then /login
  3. First run of a TUI agent shows setup modals. Answer them by hand before
     using \`ask\`, or the harness will type your prompt into a menu:
       agentmux spawn rev --cli claude --cwd .
       tmux -L agentmux attach -t rev      # answer modals, then Ctrl-b d
  4. Desktop notices use Notification Center; allow "Script Editor" / your
     terminal in System Settings > Notifications if they do not appear.
NEXT_MAC
  exit 0
fi

cat <<'NEXT'

Next steps
  1. Share credentials/config with the Windows installs (optional):
       ./link-windows-state.sh --check
       ./link-windows-state.sh --apply
  2. Log in to each agent CLI inside WSL (interactive, one time):
       codex login
       claude          # then /login
  3. First run of a TUI agent shows setup modals. Answer them by hand before
     using `ask`, or the harness will type your prompt into a menu:
       agentmux spawn rev --cli claude --cwd .
       tmux -L agentmux attach -t rev      # answer modals, then Ctrl-b d
  4. Read ANALYSIS_2026-09-18.md before trusting any answer this tool relays.
NEXT
