import importlib.util,json,subprocess,hashlib
from pathlib import Path
root=Path('/home/ryan/.cache/agentmux-governance/p01-dashboard-windows-isolation-w8n2bhwv');home=root/'codex';env={'PATH':'/usr/local/bin:/usr/bin:/bin','HOME':str(root),'CODEX_HOME':str(home),'LANG':'C.UTF-8'};wrapper=Path('/home/ryan/.local/share/agentmux/windows-clients/forward.py');spec=importlib.util.spec_from_file_location('forward',wrapper);m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);config=json.loads((wrapper.parent/'clients.json').read_text())['codex']
(home/'p01-private.config.toml').write_text('p01_private_profile_sentinel=true\n')
args=['codex','exec','--strict-config','--profile','p01-private','--skip-git-repo-check','noop'];r=subprocess.run(args,env=env,cwd=root,capture_output=True,text=True,stdin=subprocess.DEVNULL,timeout=30);(root/'private-profile-rejection.log').write_text(r.stdout+r.stderr);assert r.returncode!=0 and 'p01_private_profile_sentinel' in r.stderr and 'p01-private.config.toml' in r.stderr
probe="console.log(JSON.stringify({CODEX_HOME:process.env.CODEX_HOME,providerEnvPresent:['OPENAI_API_KEY','CODEX_CUSTOM_API_KEY','ANTHROPIC_API_KEY','P01_MISSING_PROVIDER_KEY'].some(k=>!!process.env[k])}))";windows_env=json.loads(subprocess.check_output([config['exe'],'-e',probe],env=m.environment(env),text=True));assert not windows_env['providerEnvPresent']
version=subprocess.check_output(['codex','--version'],env=env,text=True).strip()
report={'windowsVersion':version,'windowsEnvironment':windows_env,'wrapperSha256':hashlib.sha256(wrapper.read_bytes()).hexdigest(),'clientsSha256':hashlib.sha256((wrapper.parent/'clients.json').read_bytes()).hexdigest(),'configSentinelRejectedFromPrivatePath':'p01_private_configuration_sentinel' in (root/'private-config-rejection.log').read_text(),'profileSentinelRejectedFromPrivatePath':True,'validProfileRuntimeResult':'Windows state initialization failed over Linux UNC; not a missing-key validation pass.','inferencePerformed':False,'defaultCredentialFilesOpenedByHarness':False,'scope':'Proves explicit private config and profile path routing through Windows-backed client. No OS-wide file-access tracing; Windowsruntime onUNC not qualified.','logs':{p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in root.glob('*.log')}}
(root/'isolation-result.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
