from pathlib import Path
import importlib.util,json,subprocess,tempfile,hashlib,shutil,os
root=Path('/home/ryan/.cache/agentmux-governance/windows-cli-links/20261009-192119');durable=Path.home()/'.local/share/agentmux/windows-clients';spec=importlib.util.spec_from_file_location('forward',durable/'forward.py');f=importlib.util.module_from_spec(spec);spec.loader.exec_module(f)
a='/tmp/first dir';b='/tmp/second dir';wa=f.windows_path(a);wb=f.windows_path(b)
cases=[('claude',['--add-dir',a,b,'--model','m','--','/tmp/prompt'],['--add-dir',wa,wb,'--model','m','--','/tmp/prompt']),('claude',['--mcp-config','{"a":"/tmp/text"}',a,b,'--help'],['--mcp-config','{"a":"/tmp/text"}',wa,wb,'--help']),('codex',['--image',a+','+b,a,'--','/tmp/prompt'],['--image',wa+','+wb,wa,'--','/tmp/prompt']),('codex',['-i'+a+','+b,'-C'+a,'--','/tmp/prompt'],['-i'+wa+','+wb,'-C'+wa,'--','/tmp/prompt'])]
for client,args,expected in cases:
 actual=f.command(client,args);prefix=2 if client=='codex' else 1;assert actual[prefix:]==expected,(actual,expected)
with tempfile.TemporaryDirectory(prefix='forward-restore-proof-') as name:
 fixture=Path(name);target=fixture/'target';target.write_text('installed');backup=fixture/'backup';backup.write_text('corrupted');shutil.copyfile(root/'restore.py',fixture/'restore.py');manifest={'entries':[{'path':str(target),'type':'file','backup':str(backup),'originalMode':0o600,'originalUid':os.getuid(),'originalGid':os.getgid(),'originalSha256':hashlib.sha256(b'original').hexdigest(),'installedSha256':hashlib.sha256(b'installed').hexdigest()}]};(fixture/'restore-manifest.json').write_text(json.dumps(manifest));r=subprocess.run(['python3',str(fixture/'restore.py')],capture_output=True,text=True);assert r.returncode!=0 and 'Backup changed' in r.stderr and target.read_text()=='installed'
proof={'durableRoot':str(durable),'forwardSha256':hashlib.sha256((durable/'forward.py').read_bytes()).hexdigest(),'clientsSha256':hashlib.sha256((durable/'clients.json').read_bytes()).hexdigest(),'variadicPathCasesPassed':len(cases),'backupCorruptionRejectedBeforeAnyRestoreWrite':True,'liveRestoreExecuted':False,'codexParserSource':'https://raw.githubusercontent.com/openai/codex/main/codex-rs/utils/cli/src/shared_options.rs','codexParserBasis':'Official source declares comma delimiter and num_args=1..; installed 0.162.1 help declares --image <FILE>... . Main source is reference, not an assertion that it is the installed binary exact revision.','claudeParserBasis':'Installed 2.1.296 help declares --add-dir and --mcp-config variadic; --plugin-dir is single/repeatable.'}
(root/'review-fixes-verification.json').write_text(json.dumps(proof,indent=2)+'\n');print(json.dumps(proof,indent=2))
for name in ['verify.py','config-verify.py']:
 p=root/name;s=p.read_text().replace("root/'forward.py'","Path('/home/ryan/.local/share/agentmux/windows-clients/forward.py')");p.write_text(s)
p=root/'README.md';s=p.read_text();s+='\nLive launcher and client map are stored durably at /home/ryan/.local/share/agentmux/windows-clients, not in the evidence cache. All fourteen symlinks target its forward.py. Backups and historical setup evidence remain in the cache. Variadic Claude path options and Codex comma-separated/variadic image arguments have focused checks. Restore verifies both installed entries and original backup hashes before changing anything.\n';p.write_text(s)
for name,source in [('finalize.py','agentmux-forward-finalize.py'),('review-fixes-verify.py','agentmux-forward-review-fixes.py')]:
 src=Path('/mnt/c/Users/RyanHelms/AppData/Local/Temp')/source
 if src.exists():shutil.copyfile(src,root/name)