#!/usr/bin/env bash
# circle.sh - administer a federation circle (one NATS account) with nsc.
# docs/FEDERATION.md section 4. Run by the circle admin, not by every peer.
#
#   circle.sh init <circle>            operator + SYS + circle account (JetStream on) + admin user
#   circle.sh add <peer>               a member, with publish rights that name the peer; prints the creds path
#   circle.sh revoke <peer>            revoke the member's JWT and push the account (server disconnects them)
#   circle.sh helm-values              render .generated/auth-values.yaml for helm (-f)
#   circle.sh streams [--replicas N]   create the streams and KV buckets, as admin
#   circle.sh creds <peer>             path of a member's creds file
#   circle.sh push                     push the circle account JWT to the cluster's resolver
#   circle.sh server-conf <file> <port> <store_dir>   a standalone nats-server config (tests, no TLS)
#
# State lives in $AGENTMUX_CIRCLE_DIR (default deploy/nats/.generated/circle), mode 0700.
# It holds the operator and account SIGNING KEYS: back it up, never commit it.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
STATE="${AGENTMUX_CIRCLE_DIR:-$HERE/.generated/circle}"
URL="${NATS_URL:-tls://127.0.0.1:4222}"
PY="$REPO/.venv/bin/python"; [ -x "$PY" ] || PY=python3
OPERATOR=agentmux

N() { nsc --config-dir "$STATE/cfg" --data-dir "$STATE/store" --keystore-dir "$STATE/keys" "$@"; }
die() { echo "circle.sh: $*" >&2; exit 1; }
circle() { cat "$STATE/circle" 2>/dev/null || die "no circle yet: circle.sh init <name>"; }
check_name() { [[ "$1" =~ ^[a-z0-9_]{1,32}$ ]] || die "'$1' must match [a-z0-9_]{1,32} (it becomes a subject token)"; }

cmd_init() {
  local c="${1:-}"; [ -n "$c" ] || die "init needs a circle name"; check_name "$c"
  [ -e "$STATE/circle" ] && die "already initialised ($(circle)) in $STATE"
  mkdir -p "$STATE"; chmod 700 "$STATE"
  N add operator --generate-signing-key --sys --name "$OPERATOR" >/dev/null
  N edit operator --require-signing-keys --account-jwt-server-url "$URL" >/dev/null
  N add account "$c" >/dev/null
  N edit account "$c" --sk generate --js-tier 0 --js-mem-storage 256M --js-disk-storage 5G \
      --js-streams -1 --js-consumer -1 >/dev/null
  echo "$c" > "$STATE/circle"
  # The admin manages streams; members cannot (section 4).
  N add user -a "$c" -n admin >/dev/null
  N generate creds -a "$c" -n admin > "$STATE/admin.creds"; chmod 600 "$STATE/admin.creds"
  cp "$STATE/keys/creds/$OPERATOR/SYS/sys.creds" "$STATE/sys.creds"; chmod 600 "$STATE/sys.creds"
  echo "circle '$c' initialised in $STATE"
}

cmd_add() {
  local p="${1:-}"; [ -n "$p" ] || die "add needs a peer id"; check_name "$p"
  local c; c="$(circle)"
  [ "$p" = admin ] && die "'admin' is reserved"
  # Anti-spoofing (section 4): a member may publish only subjects that carry its own
  # id in token 3, and only its own presence keys. Everything a receiver trusts about
  # "who sent this" comes from that token.
  N add user -a "$c" -n "$p" \
    --allow-pub "am.*.$p.>" \
    --allow-pub "am.ctl.$p" \
    --allow-pub '$JS.API.>' \
    --allow-pub '$JS.ACK.>' \
    --allow-pub '$JS.FC.>' \
    --allow-pub '$KV.am_board.>' \
    --allow-pub "\$KV.am_presence.$p.>" \
    --allow-pub '_INBOX.>' \
    --deny-pub '$JS.API.STREAM.CREATE.>' \
    --deny-pub '$JS.API.STREAM.UPDATE.>' \
    --deny-pub '$JS.API.STREAM.DELETE.>' \
    --deny-pub '$JS.API.STREAM.PURGE.>' \
    --allow-sub '_INBOX.>' \
    --allow-sub 'am.ctl.>' >/dev/null
  N generate creds -a "$c" -n "$p" > "$STATE/$p.creds"; chmod 600 "$STATE/$p.creds"
  echo "$STATE/$p.creds"
}

cmd_push() {
  local c; c="$(circle)"
  N describe account "$c" --raw > "$STATE/$c.jwt"
  "$PY" -m hub.fed.admin push --url "$URL" --creds "$STATE/sys.creds" --ca "$(cacert)" --jwt "$STATE/$c.jwt"
}

cmd_revoke() {
  local p="${1:-}"; [ -n "$p" ] || die "revoke needs a peer id"
  local c; c="$(circle)"
  N revocations add-user -a "$c" -n "$p" >/dev/null
  cmd_push
  echo "revoked $p"
}

cacert() { echo "${NATS_CA:-$HERE/.generated/tls/ca.pem}"; }

cmd_helm_values() {
  local c; c="$(circle)"
  local out="$HERE/.generated/auth-values.yaml"
  local op sys sysjwt acct accjwt
  op="$(N describe operator --raw)"
  sys="$(N describe account SYS --json | "$PY" -c 'import json,sys;print(json.load(sys.stdin)["sub"])')"
  sysjwt="$(N describe account SYS --raw)"
  acct="$(N describe account "$c" --json | "$PY" -c 'import json,sys;print(json.load(sys.stdin)["sub"])')"
  accjwt="$(N describe account "$c" --raw)"
  cat > "$out" <<EOF
# generated by circle.sh helm-values - do not edit
config:
  merge:
    operator: $op
    system_account: $sys
    resolver_preload:
      $sys: $sysjwt
      $acct: $accjwt
EOF
  echo "$out"
}

cmd_streams() {
  "$PY" -m hub.fed.admin provision --url "$URL" --creds "$STATE/admin.creds" --ca "$(cacert)" "$@"
}

cmd_server_conf() {
  local f="${1:?file}" port="${2:?port}" store="${3:?store dir}"
  {
    echo "listen: 127.0.0.1:$port"
    echo "jetstream { store_dir: \"$store\" }"
    echo "max_payload: 2MB"
    N generate config --mem-resolver --sys-account SYS
  } > "$f"
  echo "$f"
}

cmd_creds() { local f="$STATE/${1:?peer}.creds"; [ -f "$f" ] || die "no creds for $1"; echo "$f"; }

v="${1:-}"; shift || true
cd "$REPO"
case "$v" in
  init) cmd_init "$@" ;;
  add) cmd_add "$@" ;;
  revoke) cmd_revoke "$@" ;;
  push) cmd_push ;;
  helm-values) cmd_helm_values ;;
  streams) cmd_streams "$@" ;;
  creds) cmd_creds "$@" ;;
  server-conf) cmd_server_conf "$@" ;;
  *) sed -n '2,14p' "$0"; exit 2 ;;
esac
